name: demo-apple-bria-rmbg-conversion
channels:
  - defaults
dependencies:
  - python=3.11
  - pillow=10.3.0
  - pip
  - pip:
      - coremltools==8.0b1
      - torch==2.3.1
      - torchvision
      - transformers==4.41.2
      - scikit-image==0.23.2
      - numpy<2.0.0
